enum HttpStatusCode {
  // Informational
  CONTINUE = 100,
  SWITCHING_PROTOCOLS = 101,
  PROCESSING = 102,

  // Success
  OK = 200,
  CREATED = 201,
  ACCEPTED = 202,
  NO_CONTENT = 204,
  RESET_CONTENT = 205,
  PARTIAL_CONTENT = 206,

  // Redirection
  MULTIPLE_CHOICES = 300,
  MOVED_PERMANENTLY = 301,
  FOUND = 302,
  SEE_OTHER = 303,
  NOT_MODIFIED = 304,
  TEMPORARY_REDIRECT = 307,
  PERMANENT_REDIRECT = 308,

  // Client Errors
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  METHOD_NOT_ALLOWED = 405,
  NOT_ACCEPTABLE = 406,
  CONFLICT = 409,
  GONE = 410,
  PRECONDITION_FAILED = 412,
  PAYLOAD_TOO_LARGE = 413,
  URI_TOO_LONG = 414,
  UNSUPPORTED_MEDIA_TYPE = 415,
  UNPROCESSABLE_ENTITY = 422,
  TOO_MANY_REQUESTS = 429,

  // Server Errors
  INTERNAL_SERVER_ERROR = 500,
  NOT_IMPLEMENTED = 501,
  BAD_GATEWAY = 502,
  SERVICE_UNAVAILABLE = 503,
  GATEWAY_TIMEOUT = 504,
  HTTP_VERSION_NOT_SUPPORTED = 505,
}

enum HttpStatus {
  SUCCESS = "SUCCESS",
  SERVER_ERROR = "SERVER_ERROR",
  INVALID_INPUTS = "INVALID_INPUTS",
  NOT_FOUND = "NOT_FOUND",
  USER_ALREADY_EXIST = "USER_ALREADY_EXIST",
  UPDATED = "UPDATED",
  INVALID_USER = "INVALID_USER",
  USER_CREATED = "USER_CREATED",
  UNAUTHORIZED = "UNAUTHORIZED",
  ACCOUNT_NOT_FOUND = "ACCOUNT_NOT_FOUND",
  PASSWORD_NOT_MATCHED = "PASSWORD_NOT_MATCHED",
}

export { HttpStatusCode, HttpStatus };
